### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by turikhay** [turikhay/MapModCompanion#1]
_Proposed by [Kakapo](https://discord.com/channels/1018305652294168646/1018306475589894144/1024814693631656017) in [Discord](https://discord.gg/H9ACHEqBrg)_

**Comment by UeberallGebannt** [comment]
I'd really like this feature as Velocity offers much better support for Forge in general.

**Comment by ChiAkuma** [comment]
yes pleaseeee
