### ISSUE TITLE
Unexpected world

### ISSUE THREAD

**Issue by Folas1337** [turikhay/MapModCompanion#159]
I'm not sure why but I get this error whenever I restart my server:
```
[09:21:05 INFO]: [MapModCompanion] Enabling MapModCompanion v0.10.0
[09:21:05 ERROR]: [MapModCompanion] Unexpected world: CraftWorld{name=world_builders_only}
[09:21:05 ERROR]: [MapModCompanion] For every world plugin will now send their unique IDs
[09:21:05 INFO]: [MapModCompanion] world_id handler will not be available (couldn't register incoming plugin channel: world_id (can be safely ignored on 1.13+))
```

I created world_builders_only with a void generator and MultiVerse which could be the reason but I am not sure and there isn't more in the error logs than this that would lead anywhere.

Is there any way to turn these errors off at all or perhaps something you can do about it? I'm really not sure...

**Comment by turikhay** [comment]
It is more of a warning to pinpoint issues faster if they appear.

https://github.com/turikhay/MapModCompanion/blob/621cbb247da9e85badbc88bf7e55b607cf0f22a2/spigot/src/main/java/com/turikhay/mc/mapmodcompanion/spigot/MapModCompanion.java#L157-L158

You can ignore it.

**Comment by Folas1337** [comment]
If they are more of a warning, perhaps they shouldn't be called ERROR but WARN instead? It's literally what you just called them and it would make me (and potentially others) less likely to report it as such.

Could even just be an INFO thing if you wanted but I suppose the choice is yours, just from an end user point of view I think ERROR is not a good choice.

**Comment by Folas1337** [comment]
Nvm, just now saw the commit, we're good :D
